services:
  mf-tienda-comercial:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mf-tienda-comercial
    ports:
      - "4401:80"
    networks:
      - gestor-network
    restart: unless-stopped

networks:
  gestor-network:
    external: true
